language: go

go:
  - 1.8
  - 1.9
  - "1.10"

matrix:
    fast_finish: true

before_install:
  - CWD=$(pwd)
  - go get github.com/arsonistgopher/go-netconf
  - cd $GOPATH/src/github.com/arsonistgopher/go-netconf/examples/driver

install: 
  - go get -t -v ./...

before_script:
  - cd $CWD/go-netconf
  - GO_FILES=$(find . -iname '*.go' -type f) # All the .go files,
  - go get github.com/golang/lint/golint     # Linter

script:
  - test -z $(gofmt -s -l $GO_FILES)         # Fail if a .go file hasn't been formatted with gofmt
  - go test -v ./...                         # Run all the tests with the race detector enabled
  - go vet ./...                             # go vet is the official Go static analyzer
  - golint ./...                             # one last linter
  - cd examples/driver
  - go build -v ./...		             # Specifically build the demo
