language: go

go:
  - 1.8
  - 1.9
  - "1.10"

matrix:
    fast_finish: true

install: 
  - go get -t -v ./...

before_script:
  - go get github.com/golang/lint/golint     # Linter

script:
  - diff -u <(echo -n) <(gofmt -d .)         # Run gofmt and display diff
  - go test -v ./...                         # Run all the tests with the race detector enabled
  - go vet ./...                             # go vet is the official Go static analyzer
  - golint ./...                             # one last linter
  - cd examples/driver
  - go build -v ./...		             # Specifically build the demo
