language: go

go:
  - 1.8
  - 1.9
  - "1.10"
  - master

matrix:
    fast_finish: true

install: go get -t -v ./... && go build -v ./...

script:
  - test -z $(gofmt -s -l $GO_FILES)         # Fail if a .go file hasn't been formatted with gofmt
  - go test -v ./...                         # Run all the tests with the race detector enabled
  - go vet ./...                             # go vet is the official Go static analyzer
  - golint ./...                             # one last linter
  - cd go-netconf/examples/driver
  - go build ./...		             # Specifically build the demo

before_script:
  - cd go-netconf
  - GO_FILES=$(find . -iname '*.go' -type f) # All the .go files,
  - go get github.com/golang/lint/golint     # Linter
